version: 2.1

orbs:
  maven: circleci/maven@0.0.12

jobs:
  test:
    docker:
      - image: circleci/openjdk:11.0.3-jdk-stretch
    steps:
      - checkout
      - maven/test
workflows:
  version: 2
  workflow:
    jobs:
      - test